---
- name: disable selinux
  ansible.posix.selinux:
    state: disabled

- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: false

- name: app and appadm accounts exist
  user:
    name: "{{item}}"
    state: present
  loop:
    - app
    - appadm

- name: app is in the appadm group
  user:
    name: app
    append: true
    groups:
      - appadm