---
- name: Create ckan postgres user
  become_user: postgres
  postgresql_user:
    name: ckan
    password: ckan

- name: Create datastore postgres user
  become_user: postgres
  postgresql_user:
    name: datastore
    password: datastore

- name: Create ckan database
  become_user: postgres
  postgresql_db:
    name: ckan
    encoding: UTF-8
    owner: ckan

- name: Create datastore database
  become_user: postgres
  postgresql_db:
    name: datastore
    encoding: UTF-8
    owner: ckan

- name: create system users
  user:
    name: "{{ item }}"
  loop:
    - ckan
    - datastore