---

- name: Install python dev dependencies
  yum:
    name:
      - openssl-devel
      - bzip2-devel
      - sqlite-devel
      - libcurl-devel
      - pcre-devel
      - python2-devel
      - zlib-devel
    state: present

- name: Ensure compiler is available
  yum:
    name: "@Development tools"
    state: present

- name: Create destination directory for python installation
  file:
    path: /s00/python
    state: directory
    owner: appadm
    group: appadm    

- name: Download custom python
  get_url:
    url: https://www.python.org/ftp/python/2.7.16/Python-2.7.16.tgz
    dest: /tmp/Python-2.7.16.tgz
  register: python_downloaded

- name: Extract python archive
  become_user: appadm
  unarchive:
    src: /tmp/Python-2.7.16.tgz
    dest: /tmp
    remote_src: yes

- name: Configure and install
  become_user: appadm
  shell:
    cmd: ./configure --prefix=/s00/python && make && make install
    chdir: /tmp/Python-2.7.16
    creates: /s00/python/bin/python
  tags:
    - install-python

- name: Install pip and virtualenv
  become_user: appadm
  shell:
    cmd: /s00/python/bin/python -m ensurepip && /s00/python/bin/pip install virtualenv