---
- name: Create ckan postgres user
  become_user: postgres
  postgresql_user:
    name: ckan
    password: vagrant

- name: Create datastore postgres user
  become_user: postgres
  postgresql_user:
    name: datastore
    password: vagrant

- name: Create ckan database
  become_user: postgres
  postgresql_db:
    name: ckan
    encoding: UTF-8
    owner: ckan

- name: Create datastore database
  become_user: postgres
  postgresql_db:
    name: datastore
    encoding: UTF-8
    owner: ckan

- name: create system users
  user:
    name: "{{ item }}"
  loop:
    - ckan
    - datastore

- name: solr ckan core exists
  become_user: solr
  shell:
    cmd: /opt/solr/bin/solr create_core -c ckan
    creates: /var/solr/data/ckan/core.properties

- name: solr core schema exists
  become_user: solr
  template:
    src: schema.xml.j2
    dest: /var/solr/data/ckan/conf/schema.xml

- name: restart solr
  service:
    name: solr
    state: restarted