---
- name: Create ckan postgres user
  become_user: postgres
  postgresql_user:
    name: ckan
    password: vagrant

- name: Create datastore postgres user
  become_user: postgres
  postgresql_user:
    name: datastore
    password: vagrant

- name: Create ckan database
  become_user: postgres
  postgresql_db:
    name: ckan
    encoding: UTF-8
    owner: ckan

- name: Create datastore database
  become_user: postgres
  postgresql_db:
    name: datastore
    encoding: UTF-8
    owner: ckan

- name: create system users
  user:
    name: "{{ item }}"
  loop:
    - ckan
    - datastore

- name: solr ckan core exists
  become_user: solr
  shell:
    cmd: /opt/solr/bin/solr create_core -c ckan
    creates: /var/solr/data/ckan/core.properties

- name: solr core ckan's schema is configured
  become_user: solr
  copy:
    src: schema.xml
    dest: /var/solr/data/ckan/conf/schema.xml
  tags:
    - solr-config

- name: solr core ckan is configured
  become_user: solr
  copy:
    src: solrconfig.xml
    dest: /var/solr/data/ckan/conf/solrconfig.xml
  tags:
    - solr-config

- name: solr's elevate.xml is available
  become_user: solr
  copy:
    src: elevate.xml
    dest: /var/solr/data/ckan/conf/elevate.xml
  tags:
    - solr-config

- name: restart solr
  service:
    name: solr
    state: restarted