---

- name: ckan p1 config folder exists
  file:
    path: "{{item}}"
    owner: appadm
    group: appadm
    state: directory
  loop:
    - /s00
    - /s00/etc
    - /s00/etc/ckan
    - /s00/etc/ckan/p1

- name: apps folder exists
  file:
    path: /apps
    state: directory
    owner: appadm
    group: appadm

- name: ckan folder exists
  file:
    path: /apps/ckan
    state: directory
    owner: app
    group: app

- name: logs directory for ckan exists
  file:
    path: "{{item}}"
    state: directory
    owner: app
    group: app
  loop:
    - /apps/logs
    - /apps/logs/ckanp1

- name: data dir exists
  file:
    path: "{{item}}"
    state: directory
    owner: app
    group: app
  loop:
    - /apps/ckan/upload
    - /apps/ckan/upload/p1

- name: create ckan virtualenv
  become_user: app
  pip:
    name: git+https://github.com/bcgov/ckanext-bcgov.git@{{ckanext_bcgov_version}}#egg=ckanext
    editable: true
    virtualenv: /apps/ckan/p1
    virtualenv_command: /s00/python/bin/virtualenv
    virtualenv_python: /s00/python/bin/python

- name: install ckanext-bcgov requirements
  become_user: app
  pip:
    requirements: /apps/ckan/p1/src/ckanext/requirements.txt
    virtualenv: /apps/ckan/p1

- name: ckan is configured
  template:
    src: ckan.ini.j2
    dest: /s00/etc/ckan/p1/ckan.ini
    owner: appadm
    group: appadm
  tags:
    - copy-config

- name: db is initialized
  become_user: app
  shell:
    cmd: >
      source /apps/ckan/p1/bin/activate
      paster --plugin=ckan db init --config /s00/etc/ckan/p1/ckan.ini
  tags:
    - init-db