---
- name: Install python prerequisites for postgres
  yum:
    name: python3-psycopg2
    state: present

- name: Check if postgres' data dir is empty
  stat:
    path: /var/lib/pgsql/9.6/data/
  register: data_dir

- name: add postgres96 rpm key
  rpm_key:
    key: https://download.postgresql.org/pub/repos/yum/RPM-GPG-KEY-PGDG-96
    state: present

- name: Install postgres 9.6 if the data dir is empty
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-8-x86_64/postgresql96-libs-9.6.22-1PGDG.rhel8.x86_64.rpm
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-8-x86_64/postgresql96-9.6.22-1PGDG.rhel8.x86_64.rpm
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-8-x86_64/postgresql96-devel-9.6.22-1PGDG.rhel8.x86_64.rpm
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-8-x86_64/postgresql96-server-9.6.22-1PGDG.rhel8.x86_64.rpm
    - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-8-x86_64/postgresql96-contrib-9.6.22-1PGDG.rhel8.x86_64.rpm
  when: not data_dir.stat.exists

- name: Init postgres db if the data dir is empty
  shell: /usr/pgsql-9.6/bin/postgresql96-setup initdb
  when: not data_dir.stat.exists

- name: Reload postgres service
  service:
    name: postgresql-9.6
    state: reloaded
    enabled: true
