---

- name: ensure solr dependencies are installed
  become: true
  yum:
    name:
      - java-1.8.0-openjdk-devel
      - lsof
    state: present

- name: download solr
  get_url:
    url: https://archive.apache.org/dist/lucene/solr/{{solr_version}}/solr-{{solr_version}}.tgz
    dest: /home/vagrant/solr-{{solr_version}}.tgz

- name: install solr service
  become: true
  shell:
    cmd: |
      cd /home/vagrant
      tar xzf solr-{{solr_version}}.tgz solr-{{solr_version}}/bin/install_solr_service.sh --strip-components=2
      ./install_solr_service.sh solr-{{solr_version}}.tgz -f -n

- name: configure solr to start on boot
  become: true
  service:
    name: solr
    state: started
    enabled: true