---

- name: ckan p1 config folder exists
  file:
    path: "{{item}}"
    owner: appadm
    group: appadm
    state: directory
  loop:
    - /s00
    - /s00/etc
    - /s00/etc/ckan
    - /s00/etc/ckan/p1

- name: apps folder exists
  file:
    path: /apps
    state: directory
    owner: appadm
    group: appadm

- name: ckan folder exists
  file:
    path: /apps/ckan
    state: directory
    owner: app
    group: app

- name: logs directory exists
  file:
    path: /apps/logs
    state: directory
    owner: app
    group: app

- name: logs directory for ckan exists
  file:
    path: /apps/logs/ckanp1
    state: directory
    owner: app
    group: app

- name: create ckan virtualenv
  become_user: app
  pip:
    name: git+https://github.com/bcgov/ckanext-bcgov.git@{{ckanext_bcgov_version}}#egg=ckanext
    editable: true
    virtualenv: /apps/ckan/p1
    virtualenv_command: /s00/python/bin/virtualenv
    virtualenv_python: /s00/python/bin/python

- name: install ckanext-bcgov requirements
  become_user: app
  pip:
    requirements: /apps/ckan/p1/src/ckanext/requirements.txt
    virtualenv: /apps/ckan/p1

- name: Create ckan postgres user
  become_user: postgres
  postgresql_user:
    name: ckan
    password: ckan

- name: Create datastore postgres user
  become_user: postgres
  postgresql_user:
    name: datastore
    password: datastore    

- name: Create ckan database
  become_user: postgres
  postgresql_db:
    name: ckan
    encoding: UTF-8
    owner: ckan

- name: Create datastore database
  become_user: postgres
  postgresql_db:
    name: datastore
    encoding: UTF-8
    owner: ckan

- name: create system users
  user:
    name: "{{ item }}"
  loop:
    - ckan
    - datastore