---
- name: set up database server
  hosts: db
  become: true
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: copy cfdisk script
      copy:
        src: configuresda1
        dest: /configuresda1

    - name: resize main partition
      shell:
        cmd: sfdisk /dev/sda --force < /configuresda1

    - name: register updates
      shell:
        cmd: partx -u /dev/sda

    - name: expand disk
      shell:
        cmd: xfs_growfs /

  roles:
    - common
    - psql
    - solr
    - name: ckandb
      tags: ckandb