---
- name: initialize empty ckan database
  hosts: web
  become: true
  become_user: app
  tasks:
    - name: use paster to initialize empty database
      shell:
        chdir: /apps/ckan
        cmd: |
          source /apps/ckan/p1/bin/activate
          paster --plugin=ckan db init -c /s00/etc/ckan/p1/ckan.ini
          paster --plugin=ckan search-index rebuild -c /s00/etc/ckan/p1/ckan.ini