---
- name: redis is installed
  become: true
  dnf:
    name: redis
    state: present

- name: redis service is enabled
  become: true
  service:
    name: redis
    state: started
    enabled: true